site_name: Conversational Components Docs 
nav:
  - Overview: index.md
  #- Tutorials:
  #    - How to integrate a component with RASA: tutorials/rasa.md
  - Video Tutorials: 
    - Marketplace: tutorials/videos.md
    - Developers: tutorials/developer_videos.md
    - Authors: tutorials/authors_videos.md
  - Chatbot Developers:
    - SDKs: SDKs.md
  - Component Authors:
    - Vendor Toolkits: connectors.md
    - Publishing guidelines: vendor-guidelines.md
  - API Spec: api.md
  - ⬅️ Home: https://conversationalcomponents.com/
  - ⬅️ Marketplace: https://marketplace.conversationalcomponents.com/

repo_url: 'https://github.com/conversationalcomponents/docs'

theme:
  name: material

markdown_extensions:
  - codehilite

extra:
  social:
    - type: 'github'
      link: 'https://github.com/conversationalcomponents'
    - type: 'facebook'
      link: 'https://facebook.com/ConversationalComponents'
